CREATE TABLE files
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    user_id       BIGINT                                    NOT NULL,
    file_type     VARCHAR(20)                               NOT NULL,
    file_name     VARCHAR(255)                              NOT NULL,
    storage_path  VARCHAR(255)                              NOT NULL,
    original_size BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_files PRIMARY KEY (id)
);

CREATE TABLE jobs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    file_id            BIGINT                                    NOT NULL,
    manipulation_query TEXT,
    status             VARCHAR(20)                               NOT NULL,
    result_path        VARCHAR(255),
    processed_size     BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    completed_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_jobs PRIMARY KEY (id)
);

ALTER TABLE files
    ADD CONSTRAINT FK_FILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE jobs
    ADD CONSTRAINT FK_JOBS_ON_FILE FOREIGN KEY (file_id) REFERENCES files (id);

ALTER TABLE files
    ADD CONSTRAINT chk_file_type CHECK (file_type IN ('CSV', 'JSON', 'XML'));

ALTER TABLE jobs
    ADD CONSTRAINT chk_job_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'));