CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    user_id    BIGINT                                    NOT NULL,
    job_id     BIGINT                                    NOT NULL,
    read       BOOLEAN                     DEFAULT FALSE NOT NULL,
    message    TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE INDEX idx_notifications_user_read_createdAt ON notifications (user_id, read, created_at);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_JOB FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);